### ISSUE TITLE
Which uarch is this model referring to?

### ISSUE THREAD

**Issue by cnjsdfcy** [nietzhuang/Eyeriss-unfinished#1]
Hi there,

As mentioned in the title, which version of eyeriss are you targeting? Eyeriss V1 or Eyeriss V2?

Thanks,
Yu

**Comment by nietzhuang** [comment]
Dear Caiyu,

Currently, it's only targeted on version 1.
In Eyeriss v2, you could see there's innovative NoC design attached by several Eyeriss v1 circuits.

Yours sincerely,

**Comment by cnjsdfcy** [comment]
Thanks for your reply, Nietz. And also thanks for providing this cycle-accurate systemc model as a good learning material.

**Comment by nietzhuang** [comment]
Appreciate for your feedback. It's very important for me.
