### ISSUE TITLE
Strange timing

### ISSUE THREAD

**Issue by cnjsdfcy** [nietzhuang/Eyeriss-unfinished#2]
Hi Nietz,

I found that the systemc model's timing seems problematic, e.g as below screenshot:
![image](https://user-images.githubusercontent.com/5670527/133279024-a1d6d753-acb4-4118-a9f8-77e46395797b.png)

Shouldn't it be that the input _weight_ of MAC_1_0 be 1 cycle after the output _w_ of RegFile_1_0?

In my understand of systemc, the sc_signal between these two module's sc_out/sc_in port, should bring in 1 cylce delay, but it didn't.

**Comment by nietzhuang** [comment]
Dear Caiyu, 

Actually, concerning signals which are w (sc_out) and weight (sc_in) design in SC_METHOD since it'll be used as a combinational path from the gate-level perspective.
The delay for 1 cycle would be observed when uses sc_signal in SC_THREAD directive. Notice the sc_signal.read() .

**Comment by cnjsdfcy** [comment]
Hi Nietz,

Do you plan to upgrade this (functional) model to a cycle-accurate model?

Thanks,
Cai Yu

**Comment by nietzhuang** [comment]
Dear Cai Yu,

Which function do you mention exactly?
